name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch
      env: 
        DOLCESDK: /usr/local/dolcesdk
        PATH: /usr/local/dolcesdk/bin:PATH
      run: git clone https://github.com/dolcesdk/ddpm && cd ddpm && ./bootstrap-dolcesdk.sh && ./install-all.sh
    - name: cmake
      run: cmake
    - name: make
      run: mkdir build && cd build && make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
